# -*- coding: utf-8 -*-
"""registro centro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8GgRIJR91pVfFEbFQDnalXAeEleKfT5
"""



import streamlit as st
from utils.auth import register_user
from utils.queries import insert_data
from config import supabase

st.title("Registro de Centro Deportivo")

with st.form("venue_registration_form"):
    st.subheader("Datos de acceso")
    email = st.text_input("Correo electrónico")
    password = st.text_input("Contraseña", type="password")

    st.subheader("Datos del centro")
    name = st.text_input("Nombre comercial")
    vat = st.text_input("CIF o VAT")
    company = st.text_input("Razón social")
    address = st.text_input("Dirección")
    postal_code = st.text_input("Código postal")
    city = st.text_input("Ciudad")
    lat = st.number_input("Latitud", format="%.6f")
    lon = st.number_input("Longitud", format="%.6f")
    website = st.text_input("Web")
    instagram = st.text_input("Instagram")
    facebook = st.text_input("Facebook")
    twitter = st.text_input("Twitter")
    tiktok = st.text_input("TikTok")
    phone = st.text_input("Teléfono")
    venue_type = st.selectbox("Tipo de centro", ["Club", "Tienda", "Otro"])
    accessibility = st.checkbox("¿Tiene accesibilidad física?")
    languages = st.text_input("Idiomas hablados")

    submitted = st.form_submit_button("Registrar")

    if submitted:
        # 1. Crear usuario en auth
        auth_res = register_user(email, password, role="venue")

        if auth_res and auth_res.user:
            auth_user_id = auth_res.user.id

            # 2. Crear perfil en tabla venues
            venue_data = {
                "auth_user_id": auth_user_id,
                "name": name,
                "vat_number": vat,
                "company_name": company,
                "address": address,
                "postal_code": postal_code,
                "city": city,
                "latitude": lat,
                "longitude": lon,
                "website": website,
                "instagram": instagram,
                "facebook": facebook,
                "twitter": twitter,
                "tiktok": tiktok,
                "phone": phone,
                "email": email,
                "venue_type": venue_type,
                "accessibility": accessibility,
                "languages_spoken": languages
            }

            db_res = insert_data("venues", venue_data)

            if "error" not in db_res:
                st.success("Centro deportivo registrado correctamente. Ya puedes añadir tus actividades.")
            else:
                st.error(f"Error al guardar el centro: {db_res['error']}")
        else:
            st.error("No se pudo crear el usuario. ¿Ya existe ese correo?")