# -*- coding: utf-8 -*-
"""Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_5MrJlgoAdfOTVRHJNUxYI66KbWBE-b
"""

import streamlit as st

st.title("Bienvenido FYT")

st.markdown("### ¿Listo para encontrar tu próximo FYT?")
perfil = st.radio("Selecciona tu perfil:", ["Centro Deportivo", "Deportista"])

if perfil == "Centro Deportivo":
    st.markdown("""
    Como centro deportivo podrás:
    - Registrar tus instalaciones
    - Publicar las actividades y clases que ofreces
    """)
    st.page_link("pages/3_RegistroCentro.py", label="👉 Ir al registro de Centro Deportivo")

elif perfil == "Deportista":
    st.markdown("""
    Como deportista podrás:
    - Crear tu perfil con tus preferencias
    - Encontrar actividades que se adapten a tus intereses
    """)
    st.page_link("pages/4_RegistroDeportista.py", label="👉 Ir al registro de Deportista")
