# -*- coding: utf-8 -*-
"""auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZuUZzHnp_S_m9i0TEvWytFpYTwtLFN5
"""

import streamlit as st
from supabase import create_client, Client

def login_user(email, password):
    try:
        res = supabase.auth.sign_in_with_password({
            "email": email,
            "password": password
        })
        if res.user:
            return {
                "user_id": res.user.id,
                "email": res.user.email,
                "role": res.user.user_metadata.get("role", None)
            }
    except Exception as e:
        return None

def register_user(email, password, role):
    try:
        res = supabase.auth.sign_up({
            "email": email,
            "password": password,
            "options": {
                "data": {"role": role}
            }
        })
        return res
    except Exception as e:
        return None